# -*- coding: utf-8 -*-
"""audio amplitudes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ge-AjglplgGh5H-jAfBUrcC9r_K95gk5
"""

import warnings
warnings.filterwarnings("ignore")

# from google.colab import drive

# drive.mount('/content/gdrive/')

import librosa
import cv2

def get_amplitudes(videoURL,fps,length):
  # cap = cv2.VideoCapture(videoURL)
  # length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
  # fps = cap.get(cv2.CAP_PROP_FPS)
  # cap.release()
  # cv2.destroyAllWindows()
  y, sr = librosa.load(videoURL,sr=fps)
  x = y*y
  return x[:length]

# z = get_amplitudes('/content/gdrive/MyDrive/third person shooter/realm royale_Trim.mp4')

